apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      repoRef:
        name: kf-manifests
        path: openshift/openshift-scc
    name: openshift-scc
  # Istio install. If not needed, comment out istio-crds and istio-install.
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: kf-manifests
        path: istio/istio-crds
    name: istio-crds
  - kustomizeConfig:
      overlays:
      - openshift
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: kf-manifests
        path: istio/istio-install
    name: istio-install
  # This component is the istio resources for Kubeflow (e.g. gateway), not about installing istio.
  - kustomizeConfig:
      parameters:
      - name: clusterRbacConfig
        value: "OFF"
      repoRef:
        name: kf-manifests
        path: istio/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ai-library/cluster
    name: ai-library-cluster
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: ai-library/operator
    # Note:  In order to utilize ai-library, you also need to have Seldon installed    
    name: ai-library-operator
  - kustomizeConfig:
      parameters:
      # Note: The admin username is admin
      - name: SUPERSET_ADMIN_PASSWORD
        value: admin
      repoRef:
        name: manifests
        path: superset
    name: superset
  - kustomizeConfig:
      parameters:
      repoRef:
        name: manifests
        path: superset
    name: superset
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: openshift-operators
      repoRef:
        name: manifests
        path: kafka/cluster
    name: strimzi-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kafka/kafka
    name: kafka-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/cluster
    name: grafana-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/grafana
    name: grafana-instance
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: radanalyticsio/spark/cluster
    name: radanalyticsio-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: radanalyticsio/spark/operator
    name: radanalyticsio-spark-operator
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: cert-manager
      repoRef:
        name: kf-manifests
        path: cert-manager/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: kube-system
      repoRef:
        name: kf-manifests
        path: cert-manager/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      overlays:
      - self-signed
      parameters:
      - name: namespace
        value: cert-manager
      repoRef:
        name: kf-manifests
        path: cert-manager/cert-manager
    name: cert-manager
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: kubeflow
      repoRef:
        name: kf-manifests
        path: seldon/seldon-core-operator
    name: seldon-core-operator
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: kf-manifests
        path: common/centraldashboard
    name: centraldashboard
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: prometheus/cluster
    name: prometheus-cluster
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: prometheus/operator
    name: prometheus-operator
  repos:
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/master
  - name: kf-manifests
    uri: https://github.com/opendatahub-io/manifests/tarball/v0.7-branch-openshift
  version: v0.7-branch-openshift